### ISSUE TITLE
Submit on navigate

### ISSUE THREAD

**Issue by tabolario** [schneems/wicked#156] opened 2015-01-06 22:10 UTC
Hi @schneems, I'm looking to use something like wicked for a piece of functionality that has a linear progression but allows you to skip back and forth (kind of like Turbo Tax). The main thing I'm trying to figure out is how to have the form for each step view submit every time you navigate to another step. As this kind of functionality doesn't seem to be built-in, do you have any suggestions on how one might go about implementing this on top of wicked, or is wicked not really designed for this use case? Thanks!

@tphang

**Comment by schneems** [comment] 2015-01-06 22:15
> how to have the form for each step view submit every time you navigate to another step

It hits update every time you hit submit on a form. If you do it right you should get backwards/forwards functionality for free using wicked.

**Comment by tabolario** [comment] 2015-01-07 05:40
@schneems Thanks for the quick reply! So one of the main things the built-in functionality didn't seem to provide was a way to submit the form on any sort of step navigation (like a navigation bar that that lets you jump to any step). My solution to this today ended up being a React component that renders links to steps, but handles the click event by injecting a hidden field indicating the step target into the form and then submitting it, which the update action then consumes in order to inform the redirect:

**React component (could be easily done with other JS libraries:**
```javascript
var component = React.createClass({
  propTypes: {
    label: React.PropTypes.string.isRequired,
    target: React.PropTypes.string.isRequired
  },

  render: function() {
    return(<a href="#" onClick={this.handleClick}>{this.props.label}</a>);
  },

  handleClick: function() {
    var form = $('.edit_submission').first();
    form.append('<input type="hidden" name="target" value="' + this.props.target + '">');
    form.submit();
  }
});

window.StepLink = component;

export default component;
```

**Helper to render the component:**
```ruby
def link_to_submission_step(label, step)
  react_component('StepLink', { label: label, target: step });
end
```

**Update action (abridged):**
```ruby
class SubmissionUpdatesController < ActionController::Base
  include Wicked::Wizard

  steps :step_one, :step_two

  def update
    update_submission = UpdateSubmission.call(submission: submission, params: submission_params)
    if update_submission.success?
      redirect_to wizard_path(target_step)
    else
      render_step(step)
    end
  end

  private

  ...

  def target_step
    (params[:target] || next_step).to_sym
  end
```

This seems to work pretty well so far!

**Comment by tabolario** [comment] 2015-01-07 05:46
Oops, forgot to show an example of a step template with this:

**Step two template:**
```html
<nav> <!-- Actually in a partial -->
  <ul>
    <li><%= link_to_submission_step 'Step One', :step_one %></li>
    <li><%= link_to_submission_step 'Step Two', :step_two %></li>
    <li><%= link_to_submission_step 'Step Three', :step_three %></li>
    <li><%= link_to_submission_step 'Step Four', :step_four %></li>
    <li><%= link_to_submission_step 'Step Five', :step_five %></li>
</nav>

<%= form_for submission, url: wizard_path do |f| %>
  ...
<% end %>

<nav> <!-- Something like paginate_submission_steps as a helper -->
  <ul>
    <li><%= link_to_submission_step raw('&laquo; Step One'), :step_one %></li>
    <li><%= link_to_submission_step 'Save progress', :step_two %></li>
    <li><%= link_to_submission_step raw('Step Two &raquo;'), :step_three %></li>
  </ul>
</nav>
```

**Comment by schneems** [comment] 2015-01-07 18:00
Sounds good. Going to close this as not a bug :smile:

**Closed by schneems** 2015-01-07 18:00 UTC
